-- Migration: Create chat_webhook_events table for Timelines AI webhooks
-- Run this in Supabase SQL Editor

create table if not exists public.chat_webhook_events (
  id          bigint generated by default as identity primary key,
  event_type  text        not null,
  chat_id     text        not null,
  message_uid text,
  payload     jsonb,
  created_at  timestamptz default now()
);

-- Enable Row Level Security
alter table public.chat_webhook_events enable row level security;

-- Allow the Edge Function (service role) to insert events
create policy "service role can insert"
  on public.chat_webhook_events
  for insert
  to service_role
  with check (true);

-- Allow authenticated users to read events (for Realtime subscription)
create policy "authenticated can read"
  on public.chat_webhook_events
  for select
  to authenticated
  using (true);

-- Auto-cleanup: delete events older than 24h to keep the table small
create or replace function public.cleanup_old_webhook_events()
returns void
language plpgsql
security definer
as $$
begin
  delete from public.chat_webhook_events
  where created_at < now() - interval '24 hours';
end;
$$;

-- Enable Realtime on this table
-- (You also need to add it in Supabase Dashboard → Database → Replication)
comment on table public.chat_webhook_events is 'Timelines AI webhook events for real-time chat updates';
